id: A0F14CC5B
title: The Guru Yoga of the Profound Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.338838
  last_modified_at: 2022-03-01 06:18:52.338841
