id: A0F14CC5B
title: The Lament of Rudra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.339779
  last_modified_at: 2022-03-01 06:18:52.339781
