id: A0F14CC5B
title: Aspiration Prayer from Tārā Sādhana
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.246226
  last_modified_at: 2022-03-01 06:18:52.246229
