id: A0F14CC5B
title: Ārya Mañjuśrī Tantra Garbha
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.434968
  last_modified_at: 2022-03-01 06:18:52.434971
