id: A0F14CC5B
title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
  ‘The Heart Essence of the Sublime Lady of Immortality’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.244405
  last_modified_at: 2022-03-01 06:18:52.244408
