id: A0F14CC5B
title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed Instructions'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.189449
  last_modified_at: 2022-03-01 06:18:52.189454
