id: A0F14CC5B
title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.239951
  last_modified_at: 2022-03-01 06:18:52.239954
