id: A0F14CC5B
title: Vajrakīla Tsok Prayer from Sangtik Korsum
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.422891
  last_modified_at: 2022-03-01 06:18:52.422894
