id: A0F14CC5B
title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart Essence
  of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.185840
  last_modified_at: 2022-03-01 06:18:52.185844
