id: A0F14CC5B
title: 'Transference: Enlightenment Without Meditation (root text)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.419251
  last_modified_at: 2022-03-01 06:18:52.419253
