id: A0F14CC5B
title: The Secret Practice of the Great Compassionate One, Natural Liberation of Suffering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.377030
  last_modified_at: 2022-03-01 06:18:52.377035
