id: A0F14CC5B
title: A Ritual of Blessing and Empowerment for the Female Practice, from the Heart
  Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.236432
  last_modified_at: 2022-03-01 06:18:52.236435
