id: A0F14CC5B
title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
  of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.372301
  last_modified_at: 2022-03-01 06:18:52.372304
