id: A0F14CC5B
title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
  All Obstacles on the Path'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.330752
  last_modified_at: 2022-03-01 06:18:52.330754
