id: A0F14CC5B
title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously Fulfills
  All Wishes (Sampa Lhundrupma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.299119
  last_modified_at: 2022-03-01 06:18:52.299122
