id: A0F14CC5B
title: The General Visualization for Prayers to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.337792
  last_modified_at: 2022-03-01 06:18:52.337795
