id: A0F14CC5B
title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
  Light'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.390827
  last_modified_at: 2022-03-01 06:18:52.390842
