id: A0F14CC5B
title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.354082
  last_modified_at: 2022-03-01 06:18:52.354085
