id: A0F14CC5B
title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching from
  the Lama Sangdü'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.242726
  last_modified_at: 2022-03-01 06:18:52.242729
