id: A0F14CC5B
title: The Spontaneous Vajra Song of Fulfilment and Confession
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.386905
  last_modified_at: 2022-03-01 06:18:52.386908
