id: A0F14CC5B
title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.249878
  last_modified_at: 2022-03-01 06:18:52.249882
