id: A0F14CC5B
title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of the
  Guru (Lama Sangdü)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.327250
  last_modified_at: 2022-03-01 06:18:52.327253
