id: A0F14CC5B
title: Brief Prayer of the Feast Gathering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.251484
  last_modified_at: 2022-03-01 06:18:52.251487
