id: A0F14CC5B
title: Maṇḍala Offering from Longsal Dorje Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.306076
  last_modified_at: 2022-03-01 06:18:52.306079
