id: A0F14CC5B
title: The Means for Accomplishment called the Blazing Wheel
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.342597
  last_modified_at: 2022-03-01 06:18:52.342599
