id: A0F14CC5B
title: The Abbreviated Prayer in Seven Chapters
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.320142
  last_modified_at: 2022-03-01 06:18:52.320145
