id: A0F14CC5B
title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
  of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.256156
  last_modified_at: 2022-03-01 06:18:52.256159
