id: A0F14CC5B
title: Heart of Vajrasattva—The Heart of Confession, the King of Purification Practices,
  from 'The Immaculate Secret Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.267202
  last_modified_at: 2022-03-01 06:18:52.267206
