id: A0F14CC5B
title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.336461
  last_modified_at: 2022-03-01 06:18:52.336464
