id: A0F14CC5B
title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.196855
  last_modified_at: 2022-03-01 06:18:52.196859
