id: A0F14CC5B
title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of the Vast
  Expanse
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.361072
  last_modified_at: 2022-03-01 06:18:52.361075
