id: A0F14CC5B
title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.275832
  last_modified_at: 2022-03-01 06:18:52.275835
