id: A0F14CC5B
title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.258388
  last_modified_at: 2022-03-01 06:18:52.258391
