id: A0F14CC5B
title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.291299
  last_modified_at: 2022-03-01 06:18:52.291301
