id: A0F14CC5B
title: A Glorious Garland of Great Bliss, the Root SÄdhana of the Queen of Great Bliss,
  Yumka Tsogyal, from the Heart Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.191484
  last_modified_at: 2022-03-01 06:18:52.191490
