id: A0F14CC5B
title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the Sixty
  Solitary Forms of Yamāntaka
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.344967
  last_modified_at: 2022-03-01 06:18:52.344970
