id: A0F14CC5B
title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.308842
  last_modified_at: 2022-03-01 06:18:52.308845
