id: A0F14CC5B
title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling Wishes
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.184163
  last_modified_at: 2022-03-01 06:18:52.184170
