id: A0F14CC5B
title: A Concise Recitation of the Preliminary Practice according to the New Treasure
  of Dudjom
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.187830
  last_modified_at: 2022-03-01 06:18:52.187835
