id: A0F14CC5B
title: The Aspiration of the Vajradhātu Maṇḍala
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.322324
  last_modified_at: 2022-03-01 06:18:52.322327
