id: A0F14CC5B
title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.237613
  last_modified_at: 2022-03-01 06:18:52.237616
