id: A0F14CC5B
title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.281187
  last_modified_at: 2022-03-01 06:18:52.281191
