id: A0F14CC5B
title: The Testament Prayer to Orgyen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.394680
  last_modified_at: 2022-03-01 06:18:52.394683
