id: A0F14CC5B
title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.396091
  last_modified_at: 2022-03-01 06:18:52.396094
