id: A0F14CC5B
title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.238434
  last_modified_at: 2022-03-01 06:18:52.238437
