id: A0F14CC5B
title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
  of the Sublime Lady of Immortality)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.378393
  last_modified_at: 2022-03-01 06:18:52.378399
