id: A0F14CC5B
title: 'Vajrakīla Prayer: A Rain of Accomplishments'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.421033
  last_modified_at: 2022-03-01 06:18:52.421036
