id: A0F14CC5B
title: 'Marmé Mönlam: The Light Offering Prayer'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.304391
  last_modified_at: 2022-03-01 06:18:52.304394
