id: A0F14CC5B
title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the Reality
  Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.366739
  last_modified_at: 2022-03-01 06:18:52.366741
