id: A0F14CC5B
title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great Perfection’s
  Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.332135
  last_modified_at: 2022-03-01 06:18:52.332138
