id: A0F14CC5B
title: Yeshe Tsogyal's Prayer
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.431632
  last_modified_at: 2022-03-01 06:18:52.431636
