id: A0F14CC5B
title: Prayer to Behold AmitÄbha in Dreams
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.310027
  last_modified_at: 2022-03-01 06:18:52.310030
