id: A0F14CC5B
title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:18:52.307183
  last_modified_at: 2022-03-01 06:18:52.307186
